[
  {"lib/iteraptor/array.ex", :warn_unknown},
  {":0:unknown_function Function Derivable.Atom.__impl__/1 does not exist."},
  {":0:unknown_function Function Derivable.BitString.__impl__/1 does not exist."},
  {":0:unknown_function Function Derivable.Float.__impl__/1 does not exist."},
  {":0:unknown_function Function Derivable.Function.__impl__/1 does not exist."},
  {":0:unknown_function Function Derivable.Integer.__impl__/1 does not exist."},
  {":0:unknown_function Function Derivable.List.__impl__/1 does not exist."},
  {":0:unknown_function Function Derivable.Map.__impl__/1 does not exist."},
  {":0:unknown_function Function Derivable.PID.__impl__/1 does not exist."},
  {":0:unknown_function Function Derivable.Port.__impl__/1 does not exist."},
  {":0:unknown_function Function Derivable.Reference.__impl__/1 does not exist."},
  {":0:unknown_function Function Derivable.Tuple.__impl__/1 does not exist."},
  {":0:unknown_function Function Iteraptable.Atom.__impl__/1 does not exist."},
  {":0:unknown_function Function Iteraptable.BitString.__impl__/1 does not exist."},
  {":0:unknown_function Function Iteraptable.Float.__impl__/1 does not exist."},
  {":0:unknown_function Function Iteraptable.Function.__impl__/1 does not exist."},
  {":0:unknown_function Function Iteraptable.Integer.__impl__/1 does not exist."},
  {":0:unknown_function Function Iteraptable.List.__impl__/1 does not exist."},
  {":0:unknown_function Function Iteraptable.Map.__impl__/1 does not exist."},
  {":0:unknown_function Function Iteraptable.PID.__impl__/1 does not exist."},
  {":0:unknown_function Function Iteraptable.Port.__impl__/1 does not exist."},
  {":0:unknown_function Function Iteraptable.Reference.__impl__/1 does not exist."},
  {":0:unknown_function Function Iteraptable.Tuple.__impl__/1 does not exist."}
]
